### ISSUE TITLE
List comprehension macro

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/proc-macro-workshop#23]
I'd like to see a basic implementation of a macro for Python-style list and map comprehensions, and decide whether it would be a better teaching example for function-like proc macros than the current `seq!` project.

Something like:

```rust
let squares_map = c![n => n*n for n in 0..100 if n % 5 != 0];
```

Suggested by @jonhoo.

**Comment by dmgolembiowski** [comment]
Here ya go

```rust
macro_rules! vecomp {
    [$expr:expr; for $pat:pat in $iter:expr $(; if $cond:expr )?] => {
        IntoIterator::into_iter($iter)
            $(
                .filter(|$pat| $cond)
            )?
            .map(|$pat| $expr)
            .collect::<Vec<_>>()
    }
}
mod tests {
    #[test]
    pub fn test_simple_prime_example() {
        fn is_prime(n: u32) -> bool {
            if n >= 2 {
                (2..n).all(|a| n % a != 0)
            } else {
                false
            }
        }
        let desired = vec![
            2, 3, 5, 7, 11, 
            13, 17, 19, 23, 29,
            31, 37, 41, 43, 47];
        let actual = vecomp![x; for x in 0..50; if is_prime(*x)];
        assert_eq!(desired, actual)
    }
    
    #[test]
    pub fn test_complex_prime_example() {
        fn is_prime(n: u32) -> bool {
            if n >= 2 {
                (2..n).all(|a| n % a != 0)
            } else {
                false
            }
        }
        let desired = vec![
            2, 3, 5, 7, 11, 
            13, 17, 19, 23, 29,
            31, 37, 41, 43, 47];
        let actual = vecomp![x; for x in vecomp![y; for y in 0..100; if is_prime(*y)]; if *x < 50];
        assert_eq!(desired, actual)
    }
    #[test]
    pub fn test_silly_prime_example() {
        fn is_prime(n: u32) -> bool {
            if n >= 2 {
                (2..n).all(|a| n % a != 0)
            } else {
                false
            }
        }
        let desired = vec![
            4, 6, 10, 14, 22, 
            26, 34, 38, 46, 58,
            62, 74, 82, 86, 94];
        let actual = vecomp![
            x + x;
            for x in vecomp![y; for y in 0..100; if is_prime(*y)]; 
            if *x < 50
        ];
        assert_eq!(desired, actual)
    }
    
}
```

(Disclaimer: [jam1garner](https://github.com/jam1garner) guided me toward this with a Socratic method of sorts.)

**Comment by Robbepop** [comment]
@dmgolembiowski While I like the simplicity of your solution there are a few problems with it:

1. It is not a declarative macro while this is a workshop about proc. macros. Note that being able to specify something as a declarative macro is not necessarily a bad thing in general.
2. It does not exactly match Python's syntax and thus is not a perfect show case for that.
3. It returns a vector that potentially allocates heap memory. I think an ideal solution would return an iterator yielding the filtered elements as it is more flexible and incurs less overhead (due to the forced allocation). From what I see your solution could easily be adjusted to meet this requirement.

Finally, @dtolnay is of course to decide about all this.

**Comment by dmgolembiowski** [comment]
> @dmgolembiowski While I like the simplicity of your solution there are a few problems with it:
> 
> 1. It is not a declarative macro while this is a workshop about proc. macros. Note that being able to specify something as a declarative macro is not necessarily a bad thing in general.
> 2. It does not exactly match Python's syntax and thus is not a perfect show case for that.
> 3. It returns a vector that potentially allocates heap memory. I think an ideal solution would return an iterator yielding the filtered elements as it is more flexible and incurs less overhead (due to the forced allocation). From what I see your solution could easily be adjusted to meet this requirement.
> 
> Finally, @dtolnay is of course to decide about all this.

👍

**Comment by jmg-duarte** [comment]
@dtolnay I implemented the most basic version here https://github.com/jmg-duarte/exhaustive-rs.

It pretty much only supports an expression followed by a `for` statement and optionally and `if`, the code is rough but I'm still trying to grasp the best practices and all feedback is welcome.

I took off the `n =>` since it's not present in the original Python comprehensions.

**Comment by dtolnay** [comment]
Revisiting this, sticking with `seq!` is sufficient coverage for function-like proc macros I think.
