### ISSUE TITLE
error: failed to download `lazy_static v1.4.0`

### ISSUE THREAD

**Issue by dfinke** [dtolnay/proc-macro-workshop#24]
### Running Windows 10

![image](https://user-images.githubusercontent.com/67258/64205274-92b70f00-ce65-11e9-8fa8-998bd6238c2b.png)

**Comment by dtolnay** [comment]
Weird error -- the lazy_static 1.4.0 on crates.io definitely does not have a \0 byte on line 1 in Cargo.toml. Could you open up `C:\Users\Douglas\.cargo\registry\src\github.com-1ecc6299db9ec823\lazy_static-1.4.0\Cargo.toml` and confirm that it looks reasonable? Maybe something got corrupted in your cargo registry cache. Try deleting all of `C:\Users\Douglas\.cargo\registry\src\github.com-1ecc6299db9ec823` and then trying `cargo test` again.

**Comment by dfinke** [comment]
Weird, the toml file was binary. Thanks for the confirmation on deleting the registry, done.
More strangeness:
error: failed to download `serde v1.0.99`

Removed the registry and tried again, same error.

![image](https://user-images.githubusercontent.com/67258/64209533-c480a380-ce6e-11e9-90c1-cf1215d3d7b6.png)

**Comment by dtolnay** [comment]
Something is wacky with your connection to crates.io that is resulting in receiving wrong data. I have seen something like this once before when an employer was MITM'ing https connections and mucking with the contents.

I am closing the issue because I don't think I will be able to debug this with you here, as it doesn't seem to be related to proc macros or this workshop. You could try asking in the Rust subreddit or discord for help debugging this.

**Comment by dfinke** [comment]
Deleted my rust install, redid it, all good. Thanks for the responses and clues.
