### ISSUE TITLE
Reference implementation of bitfield

### ISSUE THREAD

**Issue by gftea** [dtolnay/proc-macro-workshop#64]
Hi @dtolnay @alexcrichton , any reference implementation for bitfield? 
I am stucked at `04-multiple-of-8bits`, which I do not know how to emit codes based on  `#size % 8`, because we can't resolve the actual value from the expression in proc-macro,

**Comment by dtolnay** [comment]
You could try taking your question to any of the resources shown in https://www.rust-lang.org/community. Syn is one of the most widely used Rust libraries so plenty of people should be able to provide guidance.

You could also try searching through forks of this repo since some people push their work to GitHub, but this is not the intended way to consume the workshop.
